### PR TITLE
Development

### PR DESCRIPTION
**Pull request by profOnno**
Merging strugee's commits, hopefully getting the testing with vows working.

### CODE REVIEW

**Comment by strugee** [comment]
@profOnno did you want me to review this for inclusion? What happened here?

**Comment by profOnno** [comment]
I messed up. Wanted to merge your branch to mine, but had source and destination switched. I'm trying to merge some update's together to make pump.io evolve. Stepen Sekula (hope i got the name right) has some updates on the website client. And i have some things I'd like to add (some already coded).

For now i have branched from e41n main to my development branch. Then merged Stephens branch. Still got add my branches and maybe yours. One of the main things I want is to get vows run all tests and succeed. Now it stalls, app.close() keeps lingering.

**Comment by strugee** [comment]
> I'm trying to merge some update's together to make pump.io evolve.

I'm doing the same thing, but (from looking at your repo) it seems like we're taking slightly different approaches. strugee/pump.io is a fork of e14n/pump.io (not a GitHub "fork", I mean a full fork into an independent project), and I fully intend to publish on npm as a separately maintained application. If [this][1] makes sense to you, I'd love to have your help. My goal is to actively merge PRs, both new ones sent to this repo and old ones sent to e14n/pump.io.

 [1]: https://github.com/strugee/pump.io#roadmap

**Comment by strugee** [comment]
Also, you don't need to use PRs to merge others' GitHub branches.

**Pull request closed without merging**
